name: Release

on:
    push:
        tags: "*"

jobs:
    quick_checks:
        uses: ./.github/workflows/quick_checks.yml
    create_release:
        runs-on: ubuntu-24.04
        name: Create Release
        needs:
        -   quick_checks
        env:
            DISTRIBUTION_DIR: "${{ github.workspace }}/dist"
            VERSION: "${{ github.ref_name }}"
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
            with:
                python-version: 3.12
                cache: 'pip'
        -   name: Build Wheel
            run: /bin/bash ${{ github.workspace}}/scripts/build_wheel.sh
        -   name: Release
            uses: softprops/action-gh-release@v2
            with:
                files: "${{ env.DISTRIBUTION_DIR }}/pydantic_markdown*.whl"
                fail_on_unmatched_files: true
                draft: true
                generate_release_notes: true
